[target.aarch64-linux-android]
ar = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/x86/bin/i686-linux-android-ar"
linker = "/Users/hamzajadid/Workspace/rust-glue/glue_adr/NDK/x86/bin/i686-linux-android-clang"