[package]
name = "glue_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "glue"
crate-type = ["cdylib"]

[dependencies]
glue_core = { path="../glue_core/" }
wasm-bindgen = "0.2.80"