#! /bin/bash

cargo build --release --target aarch64-apple-ios
cargo build --release --target x86_64-apple-ios
cargo build --release --target aarch64-apple-ios-sim

lipo -create \
    target/x86_64-apple-ios/release/libglue.a \
    target/aarch64-apple-ios-sim/release/libglue.a \
    -output target/libglue_sim.a
