// Automatically generated by flapigen
package com.proximie.rustglueadr;


public final class AndroidGlue {

    public AndroidGlue() {
        mNativeObj = init();
    }
    private static native long init();

    public static native long android_gcd(long n, long m);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AndroidGlue(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}